# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simplecli < Formula
  desc "A simple CLI tool to explain automated homebrew deployments"
  homepage "https://github.com/lukekras"
  version "1.0.3-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukekras/simplecli/releases/download/1.0.3-beta/simplecli_Darwin_x86_64.tar.gz"
      sha256 "9f77b1c2daa407b163fdab824546b92d19d12a814508c792c7e2e43dc6f71fe3"

      def install
        bin.install "simplecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukekras/simplecli/releases/download/1.0.3-beta/simplecli_Darwin_arm64.tar.gz"
      sha256 "ad4e321face5252db62c55886f5953f4fe446cf0d27898e8052634f7ecfeb1ce"

      def install
        bin.install "simplecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lukekras/simplecli/releases/download/1.0.3-beta/simplecli_Linux_x86_64.tar.gz"
        sha256 "431c3adc7e94c4caef12ed440b3c18c8b2bbaa16b622389f9ff5779ae5ec61b7"

        def install
          bin.install "simplecli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lukekras/simplecli/releases/download/1.0.3-beta/simplecli_Linux_arm64.tar.gz"
        sha256 "2e2b57b81a782cb20da436293559f3bafefc3d7efdb1aad531228d1c56b98783"

        def install
          bin.install "simplecli"
        end
      end
    end
  end
end
