# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simplecli < Formula
  desc "A simple CLI tool to explain automated homebrew deployments"
  homepage "https://github.com/lukekras"
  version "1.0.8-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukekras/simplecli/releases/download/1.0.8-beta/simplecli_Darwin_x86_64.tar.gz"
      sha256 "0711dc637b3640a4f2ee5aba852baca83ba0679126468409c6e3fe5987e0fe2a"

      def install
        bin.install "simplecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukekras/simplecli/releases/download/1.0.8-beta/simplecli_Darwin_arm64.tar.gz"
      sha256 "73c0cd7a8986e3f2b625e1506c13d5e918c22f0e866fbaba63c29e314748ffd9"

      def install
        bin.install "simplecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lukekras/simplecli/releases/download/1.0.8-beta/simplecli_Linux_x86_64.tar.gz"
        sha256 "fa11a76093d5997252fcac18cd3eae83c131723c6aa2107c01c04f97395107b4"

        def install
          bin.install "simplecli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lukekras/simplecli/releases/download/1.0.8-beta/simplecli_Linux_arm64.tar.gz"
        sha256 "e028c62112113604da87d3eed281f0f3d05ee9f432905bd613e10ddec97a40e6"

        def install
          bin.install "simplecli"
        end
      end
    end
  end
end
