# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simplecli < Formula
  desc "A simple CLI tool to explain automated homebrew deployments"
  homepage "https://github.com/lukekras"
  version "1.0.9-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukekras/simplecli/releases/download/1.0.9-beta/simplecli_Darwin_x86_64.tar.gz"
      sha256 "bc079bdda34cedf057bdc2f5fb539290c7d827e6b6d309fe0bcd96149c8ef525"

      def install
        bin.install "simplecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukekras/simplecli/releases/download/1.0.9-beta/simplecli_Darwin_arm64.tar.gz"
      sha256 "5980a0ccec3ecfdbf67bf7b643bf386fcc74218a49dedbf95f7f4c2acb678b22"

      def install
        bin.install "simplecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lukekras/simplecli/releases/download/1.0.9-beta/simplecli_Linux_x86_64.tar.gz"
        sha256 "a64cc083726989fe045a61d797e682122ac1823ec31b8af67f82ecf763ab1b1a"

        def install
          bin.install "simplecli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lukekras/simplecli/releases/download/1.0.9-beta/simplecli_Linux_arm64.tar.gz"
        sha256 "36d50ce66aeabcb78847b3c75affdfb6c661b978d42831e2db1dc2ebe4944c5f"

        def install
          bin.install "simplecli"
        end
      end
    end
  end
end
